name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          # Add your test commands here
          echo "No tests defined" || true

      - name: Code Analysis (SonarQube)
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v ${{ github.workspace }}:/usr/src \
            -w /usr/src \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=my-python-project \
            -Dsonar.host.url=https://abcd1234.ngrok.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login k8s-master-codecamp24.obss.io:30003 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag my-python-app k8s-master-codecamp24.obss.io:30003/codecamp/my-python-app:latest

      - name: Push Docker image
        run: |
          docker push k8s-master-codecamp24.obss.io:30003/codecamp/my-python-app:latest
